// <auto-generated />
namespace place.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_imageVersion_to_canvas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_imageVersion_to_canvas));
        
        string IMigrationMetadata.Id
        {
            get { return "201709260343450_add_imageVersion_to_canvas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
